// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PraProjectBNI.Models;

namespace PraProjectBNI.Migrations
{
    [DbContext(typeof(PraBNIContext))]
    partial class PraBNIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PraProjectBNI.Models.Course", b =>
                {
                    b.Property<int>("IdCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Course")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaCourse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nama_Course");

                    b.HasKey("IdCourse");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("PraProjectBNI.Models.Dosen", b =>
                {
                    b.Property<int>("IdDosen")
                        .HasColumnType("int")
                        .HasColumnName("ID_Dosen");

                    b.Property<string>("NamaDosen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nama_Dosen");

                    b.HasKey("IdDosen");

                    b.ToTable("Dosen");
                });

            modelBuilder.Entity("PraProjectBNI.Models.DosenCourse", b =>
                {
                    b.Property<int>("IdDosenCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Dosen_Course")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("ID_Course");

                    b.Property<int>("IdDosen")
                        .HasColumnType("int")
                        .HasColumnName("ID_Dosen");

                    b.HasKey("IdDosenCourse");

                    b.HasIndex("IdCourse");

                    b.HasIndex("IdDosen");

                    b.ToTable("Dosen_Course");
                });

            modelBuilder.Entity("PraProjectBNI.Models.Enrollment", b =>
                {
                    b.Property<int>("IdEnroll")
                        .HasColumnType("int")
                        .HasColumnName("ID_Enroll");

                    b.Property<int>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("ID_Course");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int")
                        .HasColumnName("ID_Student");

                    b.HasKey("IdEnroll");

                    b.HasIndex("IdCourse");

                    b.HasIndex("IdStudent");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("PraProjectBNI.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .HasColumnType("int")
                        .HasColumnName("ID_Student");

                    b.Property<int?>("Angkatan")
                        .HasColumnType("int");

                    b.Property<string>("Domisili")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("JenisKelamin")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("Jenis_Kelamin")
                        .IsFixedLength(true);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStudent");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("PraProjectBNI.Models.DosenCourse", b =>
                {
                    b.HasOne("PraProjectBNI.Models.Course", "IdCourseNavigation")
                        .WithMany("DosenCourses")
                        .HasForeignKey("IdCourse")
                        .HasConstraintName("FK_Dosen_Course_Course")
                        .IsRequired();

                    b.HasOne("PraProjectBNI.Models.Dosen", "IdDosenNavigation")
                        .WithMany("DosenCourses")
                        .HasForeignKey("IdDosen")
                        .HasConstraintName("FK_Dosen_Course_Dosen")
                        .IsRequired();

                    b.Navigation("IdCourseNavigation");

                    b.Navigation("IdDosenNavigation");
                });

            modelBuilder.Entity("PraProjectBNI.Models.Enrollment", b =>
                {
                    b.HasOne("PraProjectBNI.Models.Course", "IdCourseNavigation")
                        .WithMany("Enrollments")
                        .HasForeignKey("IdCourse")
                        .HasConstraintName("FK_Enrollment_Course")
                        .IsRequired();

                    b.HasOne("PraProjectBNI.Models.Student", "IdStudentNavigation")
                        .WithMany("Enrollments")
                        .HasForeignKey("IdStudent")
                        .HasConstraintName("FK_Enrollment_Student")
                        .IsRequired();

                    b.Navigation("IdCourseNavigation");

                    b.Navigation("IdStudentNavigation");
                });

            modelBuilder.Entity("PraProjectBNI.Models.Course", b =>
                {
                    b.Navigation("DosenCourses");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("PraProjectBNI.Models.Dosen", b =>
                {
                    b.Navigation("DosenCourses");
                });

            modelBuilder.Entity("PraProjectBNI.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
